= Network-integrated Pre and Post-Processing in Scientic Computing

== Introduction
This project is part of the course "M2 Project" at the University of Strasbourg. The goal of this project is to develop a network-integrated pre and post-processing tool for scientific computing. The tool is based on the Feel++ library and is designed to be used in the context of thermoelectric simulations.


== Installation
Feel free to use the provided `Dockerfile` to build a docker image with all the necessary dependencies. To do so, run the following command:
```bash
docker build -t 2024m2projectBitter:latest .
```

== Usage
To run the program sequentially, make shure you have the proper permissions:
```bash
chmod +x run_seq run
```
and run the program sequentially:
```bash
./run_seq
```
to run the program on a cluster:
```bash
./run
```

If you used the container, you can copy the results to your local machine by running:
```bash
docker ps # to get the container ID
docker cp <dockerID>:/home/feelppbd/project-bitter/np_1 /path/to/your/local/folder
```

== Results
If you dont want to run the program, you can find the results in the `thermoelectric.exports` folder. In particular, the `Export.case` file contains the results of on of our simulations.

== Authors

https://github.com/pa-senger[Pierre-Antoine Senger] + 
https://github.com/ARegardin/ARegardin[Antoine Regardin]
