name: Build LaTeX document
on: [pull_request, push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: doc/report.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: doc/report.pdf
